export const START_DRAWING_PUBLISHER = 'START_DRAWING_PUBLISHER';
export const START_DRAWING_PUBLISHER_SUCCESS = 'START_DRAWING_PUBLISHER_SUCCESS';
export const START_DRAWING_PUBLISHER_ERROR = 'START_DRAWING_PUBLISHER_ERROR';

export const END_DRAWING_PUBLISHER = 'END_DRAWING_PUBLISHER';
export const END_DRAWING_PUBLISHER_SUCCESS = 'END_DRAWING_PUBLISHER_SUCCESS';
export const END_DRAWING_PUBLISHER_ERROR = 'END_DRAWING_PUBLISHER_ERROR';

export const START_DRAWING_SUBSCRIBER = 'START_DRAWING_SUBSCRIBER';
export const START_DRAWING_SUBSCRIBER_SUCCESS = 'START_DRAWING_SUBSCRIBER_SUCCESS';
export const START_DRAWING_SUBSCRIBER_ERROR = 'START_DRAWING_SUBSCRIBER_ERROR';

export const END_DRAWING_SUBSCRIBER = 'END_DRAWING_SUBSCRIBER';
export const END_DRAWING_SUBSCRIBER_SUCCESS = 'END_DRAWING_SUBSCRIBER_SUCCESS';
export const END_DRAWING_SUBSCRIBER_ERROR = 'END_DRAWING_SUBSCRIBER_ERROR';

export const DRAWING_PUBLISHER_PUBLISH = 'DRAWING_PUBLISHER_PUBLISH';
